name: trustbank
description: TrustBank - Sistema bancario digital con generaciÃ³n de PDFs
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  go_router: ^12.1.3
  pdf: ^3.10.4
  printing: ^5.11.0
  path_provider: ^2.1.1
  intl: ^0.19.0
  google_fonts: ^6.1.0
  http: ^1.1.0
  file_picker: ^6.1.1
  shared_preferences: ^2.2.2
  image_picker: ^1.0.4
  http_parser: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/